# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2d113269bf393f796970a2eb8ad184067d88ddd644385d9a3a5d64b94f4f222b8076928d4f4aa2d25b937a47e65dc8be6959326467fad5be05f04212a49cd9

test:
  secret_key_base: 5d2a85978257ccbc7b4755bb875e913a20de373e839de93a259a9bf1685d3885d9b934b88c1e63385ed4f9b91c4c6b2487b58bd40e5fdd81378c5bb35cba456f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
